name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOS: "windows"
      GOARCH: "amd64"
      
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
          version: 7
          run_install: false          
          
    - name: Install go
      uses: actions/setup-go@v4
      with:
          go-version: '^1.13.1'
          
    - name: Install Tailwind CSS
      run: npm install -D tailwindcss
      
    - name: go build
      run: |
        cd config-back
        go env
        go build -ldflags "-s -w"
        ls
        cp settings.exe ../bin
        
    - name: npm build
      run: |
        ls
        echo "build tailwind js"
        cd tailwind
        npm run build
        
        echo "build vue"
        cd ../config-front
        pnpm install
        npm run build
        
        echo "build tailwind css"
        cd ../tailwind
        npm run build-help-page-css
        npm run build-html-tools-css
        
        echo "delete useless files"
        cd ..
        rm -rf bin/site/fonts/*.eot
        rm -rf bin/site/fonts/*.woff
        rm -rf bin/site/fonts/*.ttf
        rm -rf bin/site/fonts/*.ttf
        rm -rf bin/site/js/*.map
        
        echo "copy index.html to the templates folder of flask"
        mkdir bin/templates
        cp bin/site/index.html bin/templates/
        cp config-back/templates/script2.ahk bin/templates/
        cp config-back/templates/CustomShellMenu.ahk bin/templates/
        cp config-back/templates/help.html bin/templates/
        
    - name: modify changeBrightness window size
      run: |
        cd bin
        sed -i -z 's/        this.Y := 50/        this.Y := 10/' changeBrightness.ahk
        sed -i -z 's/        Gui Add, Text, x10 y280 w290 h20 +0x200/        Gui Add, Text, x10 y190 w290 h20 +0x200/' changeBrightness.ahk
        sed -i -z 's/        Gui Add, Text, x10 y300 w490 h20 +0x200/        Gui Add, Text, x10 y210 w490 h20 +0x200/' changeBrightness.ahk
        sed -i -z 's/        w :=  this.X + 70/        w :=  this.X + 50/' changeBrightness.ahk
        sed -i -z 's/        h :=  320/        h :=  240/' changeBrightness.ahk
        sed -i -z 's/        X += 58/        X += 65/' changeBrightness.ahk
        sed -i -z 's/        Y += 60/        Y += 43/' changeBrightness.ahk
        
    - name: copy files
      run: |
        mkdir MyKeymap
        cp -r data MyKeymap
        cp -r bin MyKeymap/bin
        cp -r shortcuts MyKeymap
        cp -r tools MyKeymap/
        cp AutoHotkey.dll MyKeymap/AutoHotkey.dll 
        cp clip_dll.dll MyKeymap/clip_dll.dll 
        cp concrt140.dll MyKeymap/concrt140.dll 
        cp msvcp140.dll MyKeymap/msvcp140.dll 
        cp msvcp140_1.dll MyKeymap/msvcp140_1.dll 
        cp msvcp140_2.dll MyKeymap/msvcp140_2.dll 
        cp msvcp140_atomic_wait.dll MyKeymap/msvcp140_atomic_wait.dll 
        cp msvcp140_codecvt_ids.dll MyKeymap/msvcp140_codecvt_ids.dll 
        cp vcamp140.dll MyKeymap/vcamp140.dll 
        cp vccorlib140.dll MyKeymap/vccorlib140.dll 
        cp vcomp140.dll MyKeymap/vcomp140.dll 
        cp vcruntime140.dll MyKeymap/vcruntime140.dll 
        cp vcruntime140_1.dll MyKeymap/vcruntime140_1.dll 
        cp vcruntime140.dll MyKeymap/bin/vcruntime140.dll 
        cp vcruntime140_1.dll MyKeymap/bin/vcruntime140_1.dll 

        cp MyKeymap.exe MyKeymap/MyKeymap.exe 
        cp SoundControl.exe MyKeymap/SoundControl.exe 
        cp font.ttf MyKeymap/font.ttf 
        cp 设置程序.lnk MyKeymap/设置程序.lnk 

    - uses: actions/upload-artifact@master
      with:
        name: MyKeymap
        path: MyKeymap
